os:
  - linux

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: osx
      compiler: clang

dist: trusty
sudo: required
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

install: |-
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    sudo apt-get -qy install libsdl2-dev libgtk-3-dev
  elif [ "$TRAVIS_OS_NAME" == "osx" ]
  then
    brew update
    brew install sdl2
  fi

script: |-
  if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  ./build.sh

deploy:
  provider: releases
  api_key:
    secure: GMwaLDv8s6KSkndBK7vfa9bkd4Opx/zNNXd0046cErGCwhtWNtU8hqcsJi0KrlO36nozDYoyDGjoXTLMYr4myY9gSRol2JGHHyQecXxYvb28QioSAeTeYa9lFcV0N7bGynMszb8ZC6dJJ4myD3panKe7dHgQz+5w+m5KedLWRNgArUE+OfeZm01gy88U6nEkt5oMsUZSW09q4x23V9I+vt+uljnJ10lNPqMoqZycwvKJYQTzs2BABbyWfHIp1S1ocnuxYALakGPwEupwJeZ55qWkgb9gXdKzOqurqTyWnRY96+XPNeyEpj+qcr1N7Q4pvOSXo0E0hBGjgUY49K8dgAC2xl5hqfFpMj9p32Z1LoOAfMtsg6pvWkW5qfpIofZZQgL72DTeHGvUyQf1WmDFaCql5ZNHI+kYKFlkefzGkJkmvnJcCHat1LpvlQ3iDex8y7ttUUva/N0jP/GnsY+8gw5gBZ4cLYxlKoooU9ETgrWHB2JZmO3lxEDKakHIUE5z+mX6VA32TsGlPB/Ajt0tCNlMZPI3YKs1Eww8DaqtlctKwnjQu0AeRhwqIZtEn9mYFrzGJDLZasVs7kBEkBzGWcEo/SaeJoTFSEd/jYlYf3jTu2s0trwu9GO0BzAIVGIzmGBq2jhb8rbzwIj0Rv2EM7oe4eUuislLNHwVVkW5gQs=
  file_glob: true
  file: OpenBoardView-*.dmg
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == osx"
