os:
  - linux

compiler:
  - gcc

dist: trusty
sudo: required
language: cpp

install: |-
  sudo add-apt-repository "deb http://fr.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse"
  sudo apt-get update
  sudo apt-get install -t xenial gcc-mingw-w64-i686 g++-mingw-w64-i686 mingw32-runtime
  wget https://www.libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz
  tar -xf SDL2-devel-2.0.4-mingw.tar.gz
  pushd SDL2-2.0.4
  sudo make cross CROSS_PATH=/usr
  popd
  sed '/^# Example binaries$/,$d' -i src/zlib/CMakeLists.txt

script: |-
  CROSS=mingw64 ./build.sh

deploy:
  provider: releases
  api_key:
    secure: ENCRYPTED_API_KEY
  file_glob: true
  file: OpenBoardView-*.dmg
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == osx"
