os:
- linux
compiler:
- clang
matrix:
  include:
  - os: linux
    compiler: gcc
    env: DEPLOY=yes DEPLOY_DEB=yes
  - os: osx
    compiler: clang
    env: DEPLOY=yes
  - os: linux
    compiler: gcc
    env: CROSS=mingw64 DEPLOY=yes
dist: trusty
sudo: required
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
install: |-
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    if [ "$CROSS" == "mingw64" ] # Cross compiling for Windows
    then
      sudo add-apt-repository "deb http://fr.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse" # We need an up-to-date MinGW
      sudo apt-get update
      sudo apt-get install -t xenial gcc-mingw-w64-i686 g++-mingw-w64-i686 mingw32-runtime
      wget https://www.libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz # Manually install the SDL2 mingw dev files
      tar -xf SDL2-devel-2.0.4-mingw.tar.gz
      pushd SDL2-2.0.4
      sudo make cross CROSS_PATH=/usr
      popd
    else
      sudo apt-get -qy install libsdl2-dev libgtk-3-dev
    fi
  elif [ "$TRAVIS_OS_NAME" == "osx" ]
  then
    brew update
    brew install sdl2
  fi
script: |-
  if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  ./build.sh
  if [ "$DEPLOY_DEB" == "yes" ]
  then
    pushd release_build
    make package
    popd
  fi
before_deploy: |-
  if [ "$TRAVIS_OS_NAME" == "osx" ]
  then
    export DEPLOY_FILES=$(ls OpenBoardView-*.dmg)
  elif [ "$CROSS" == "mingw64" ]
  then
    export DEPLOY_FILES=bin/openboardview.exe
  elif [ "$DEPLOY_DEB" == "yes" ]
  then
    export DEPLOY_FILES=$(ls OpenBoardView-*.deb)
  fi
deploy:
  provider: releases
  api_key:
    secure: Y7O1sQdog6Syc+U/+aotBCbKuQ4p0Vgu8dQvh71QZLTgETYqNkRvyzTAIVvDwI5rQrX+QHWpf/EmX4LZbcqNzY7Dgoq++MV1MwjNWVSgfCWG9RKDxzY1gLCdB7ruQoCmKqucerTSteRyvCfK/5jTQOxKDp952Tmk4F5WDRFLP1Iy5wLWLRs3MDEj+79b4sypSTsqly63mAvaDqxjUmbNR+5QHKA+1LuQDjyKr0JSKPIlYFvfvYZSRGAZ7SHUNgI+YSN+4pIuPrjlX5+SYAsRpBV4lRp+aJJ6d3DDOM9FaosPuA/bObmz/8jfVHuSVBZN5bXf2SzTczPVSjvAidsu04m5QdxURWcfj19hzdEs7cbvEwrcwB5J0Af1MfsTvz3395O5IfRxn/+n5KcqPzpYkPzCQPp6Zy2gwjYhu01ShEkqxsBX9XfND4MPCBaSxVHE2fRyFjlazLA5wbChMOVfGykv9q6s0c4lx+t6G9h0W8U1nB9U3icp3u+KdLEocstZgEVGuFgRxy2tlAdpYIzMW90/3jwvfgyIwXrWJgpfB+cn+dZbYCFYn1JLnTWLDDbb15ZPXxf4Gt0JLeGUER3DZrzsOrV24AqgoBDMKOJD2QVC9c0OGwy2KVTnL8yfz/JmXjzza5GBn0fontChOz60r8UUaiZ6kWXBrJEohakA8bM=
  file_glob: true
  file: "${DEPLOY_FILES}"
  skip_cleanup: true
  on:
    tags: true
    condition: "$DEPLOY == yes"
